image: debian:stretch

variables:

stages:
  - build

build:
  stage: build
  script:
    - ./autogen.sh
    - ./configure CFLAGS=-Werror
    - make
    - make check
    - sudo make install
    - gstd -e && gstd-client list_pipelines && gstd -k
